on: [push, pull_request]

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Ubuntu-20.04
        run: |
          docker build -f Docker/Test-Build-Ubuntu-20.04.docker .
      - name: Build Archlinux
        run: |
          docker build -f Docker/Test-Build-Archlinux.docker .
